### registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
   "name":"Doniyor2",
   "surname": "Toshpulatov2",
    "email": "jshobotayev@gmail.com",
    "password": "j20031027",
    "mainPhotoId": "689067c3-0ec4-4329-8fa1-6f7c41a2c51f"
}

### login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "obotayev@gmail.com",
  "password": "3434"
}
