###✔
POST http://localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json

{
  "email": "jshobotayev@gmail.com",
  "password": "3433"
}

###✔
POST http://localhost:8080/profile/admin/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE5ODAzMzcsImVtYWlsIjoianNob2JvdGF5ZXZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzIwNjY3MzcsImlzcyI6InlvdXR1YmUgdGVzdCBwb3J0YWwifQ.HBH_NThJL7EN8OvrPDPwRLljU9NOVZzGwx6iYDg-LzNbhA_z3nD2fV4I0m677ZBOcP6aI6m4RIYP0nM2OAU6ug
Content-Type: application/json

{
  "name": "dfghj",
  "surname": "dfghj",
  "status": "ACTIVE",
  "role": "ROLE_MODERATOR",
  "email": "shobotayev@gmail.com",
  "password": "3434"
}
###✔
GET http://localhost:8080/profile/info/4

###
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "dfghj",
  "surname": "dfghj",
  "email": "jshobotayev@gmail.com"
}

###
GET http://localhost:8080/profile/update/password
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzE5ODAzMzcsImVtYWlsIjoianNob2JvdGF5ZXZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzIwNjY3MzcsImlzcyI6InlvdXR1YmUgdGVzdCBwb3J0YWwifQ.HBH_NThJL7EN8OvrPDPwRLljU9NOVZzGwx6iYDg-LzNbhA_z3nD2fV4I0m677ZBOcP6aI6m4RIYP0nM2OAU6ug
